# Dockerfile.train
FROM python:3.12-slim
WORKDIR /app


# 更新 apt 並安裝 gcc (必要時也可以安裝 build-essential)
RUN apt-get update && apt-get install -y gcc


COPY requirements_retrain.txt ./
RUN pip install --no-cache-dir -r requirements_retrain.txt

# 複製專案檔案，包含 retrain.py
COPY . .

# 預設執行 retrain.py
CMD ["python", "retrain.py"]
