# Dockerfile.train
FROM python:3.12-slim
WORKDIR /app

# 更新 apt 並安裝必要的編譯工具與函式庫，包括 python3-distutils
RUN apt-get update && apt-get install -y \
    build-essential \
    python3-dev \
    python3-distutils \
    libatlas-base-dev \
    gfortran

COPY requirements_retrain.txt ./
RUN pip install --no-cache-dir -r requirements_retrain.txt

# 複製專案檔案，包含 retrain.py
COPY . .

# 預設執行 retrain.py
CMD ["python", "retrain.py"]
