name: Deploy locally

on:
  push:
    branches:
      - main         # 每次推送到 main 分支時觸發
      - 'feature/*'  # 每次開發新功能到 feature 分支時觸發
      - 'bugfix/*'   # 每次修復bug到bugfix分支時觸發

jobs:
  deploy:
    runs-on: [self-hosted]
    steps:

    # 1. 取用code
    - name: Checkout repository
      uses: actions/checkout@v3
    
    # 2. 切換到專案目錄
    - name: Build Docker Image
      run: |
        cd ~/1_aviation_predictionweb &&
        docker build -t python312:v1.0.01 .

    # 3. 停止或移除舊容器
    - name: Stop & Remove Old Container
      run: |
        docker stop python312_container || true
        docker rm   python312_container || true

    
    # 4. 執行新容器
    - name: Run Container
      run: |
        docker run -d -p 5001:5000 --name python312_container python312:v1.0.01
