name: Deploy locally

on:
  push:
    branches:
      - main
      - 'cpca/*'
      - 'cpcB/*'

jobs:
  deploy:
    runs-on: [self-hosted]

    # 在 job 層級聲明環境變數，透過 secrets 注入
    env:
      DB_SERVER: ${{ secrets.DB_SERVER }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}

    steps:
      # 1. 取用程式碼
      - name: Checkout repository
        uses: actions/checkout@v3


      # 2. 同步 Code 至伺服器
      - name: Sync Latest Code to Remote Directory
        run: |
          mkdir -p ~/aviation_predictionweb
          rsync -av --delete --exclude '*.csv' --exclude '.env' --exclude '*.sh' --exclude 'xgb_models' "$GITHUB_WORKSPACE"/ ~/aviation_predictionweb/

      #### A. Flask
      - name: Build Flask Image
        run: |
          cd ~/aviation_predictionweb
          docker build -t python312:v1.0.01 .

      # # 4.1 清除懸空映像檔
      # - name: Clean up Dangling Images
      #   run: docker image prune -f

      # 停止 & 移除先前容器
      - name: Stop & Remove Old Container
        run: |
          docker stop python312_container || true
          docker rm   python312_container || true

      # 執行新容器，用 job-level env 裏的變數(已由 secrets 注入)
      - name: Run Flask Container
        run: |
          docker run -d -p 5001:5000 --name python312_container \
            -e DB_SERVER=$DB_SERVER \
            -e DB_USER=$DB_USER \
            -e DB_PASSWORD=$DB_PASSWORD \
            -e DB_NAME=$DB_NAME \
            -v /home/dockeruser/aviation_predictionweb/xgb_models:/shared_volume \
            python312:v1.0.01

      #### B. Cron Job
      - name: Build Cron Image
        run: |
          cd ~/aviation_predictionweb
          docker build -f Dockerfile.push -t oil-cron:v1.0.01 .
      
      - name: Stop & Remove Old Cron Container
        run: |
          docker stop oil-cron-container || true
          docker rm oil-cron-container || true
      
      - name: Run Cron Container
        run: |
          docker run -d --name oil-cron-container \
            -e DB_SERVER=$DB_SERVER -e DB_USER=$DB_USER \
            -e DB_PASSWORD=$DB_PASSWORD -e DB_NAME=$DB_NAME \
            oil-cron:v1.0.01

      #### C. 清理懸空映像(共用)
      - name: Clean dangling images
        run: docker image prune -f
      
