name: Deploy locally

on:
  push:
    branches:
      - main
      - 'cpca/*' 
      - 'cpcb/*'

jobs:
  deploy:
    runs-on: [self-hosted]
    steps:

    # 1. 取用code
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. 複製最新code到遠端資料夾
    - name: Sync Latest Code to Remote Directory
      run: |
        mkdir -p ~/aviation_predictionweb
        rsync -av --delete --exclude '*.csv' "$GITHUB_WORKSPACE"/ ~/aviation_predictionweb/
    
    # 3. 切換到專案目錄
    - name: Build Docker Image
      run: |
        cd ~/aviation_predictionweb
        docker build -t python312:v1.0.01 .

    # 3.1 清除懸空映像檔
    - name: Clean up Dangling Images
      run: docker image prune -f

    # 4. 停止或移除舊容器
    - name: Stop & Remove Old Container
      run: |
        docker stop python312_container || true
        docker rm   python312_container || true

    
    # 5. 執行新容器
    - name: Run Container
      run: |
        docker run -d -p 5001:5000 --name python312_container python312:v1.0.01
